services:
  frontend:
    container_name: frontend-pki
    build: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
#      keycloak:
#        condition: service_healthy

  backend:
    container_name: backend-pki
    build: backend
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=${SPRING_DEVTOOLS_REMOTE_SECRET}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KEYCLOAK_AUTH_SERVER_URL=${SPRING_KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_SERVICE_NAME=${KEYCLOAK_SERVICE_NAME}
      - SECURITY_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SECURITY_ENCRYPTION_PASSPHRASE=${ENCRYPTION_PASSPHRASE}
    depends_on:
      db:
        condition: service_healthy
#      keycloak:
#        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/healthy ] || (wget --spider --quiet --no-check-certificate https://localhost:8080/actuator/health && touch /tmp/healthy)"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  db:
    container_name: db-pki
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  pgadmin:
    container_name: pgadmin-pki
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  keycloak-db:
    container_name: db-keycloak
    image: postgres:17.2-alpine
    ports:
      - "5433:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  keycloak:
    container_name: keycloak-pki
    image: quay.io/keycloak/keycloak:26.3.4
    command:
      - start-dev
      - --import-realm
      - --https-key-store-file=/opt/keycloak/conf/keycloak.p12
      - --https-key-store-password=password
    ports:
      - "8081:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8081
      - KC_DB=postgres
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_DB_URL=${KEYCLOAK_DB_URL}
      - KC_HEALTH_ENABLED=true
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers
      - ./keycloak/keycloak.p12:/opt/keycloak/conf/keycloak.p12
    depends_on:
      keycloak-db:
        condition: service_healthy

volumes:
  postgres-data:
  pgadmin-data:
  maven-repo:
  keycloak-data:
